{% set name = "safeint" %}
{% set version = "3.0.26" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dcleblanc/SafeInt/archive/refs/tags/{{ version }}.tar.gz
  sha256: 62fef99873ad975ddd8356923b3d51ed316209c1a05ac85814219373a13ae4d5

build:
  number: 5

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake {{ cmake }}
    - ninja {{ ninja }}
    - make 

test:
  commands:
    - test -f $PREFIX/include/SafeInt.hpp

about:
  home: https://github.com/dcleblanc/SafeInt 
  summary: SafeInt is a class library for C++ that manages integer overflows.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
